required-players: 2
countdown seconds: 30
lobby-spawn:
  world: 'flatroom'
  x: 53.5
  y: -59.0
  z: 24.5
  yaw: 178.6
  pitch: -1.0
arenas:
  0:
    world: 'flatroom'
    x: 45.9
    y: -59.0
    z: -0.7
    yaw: -179.4
    pitch: 0.8
  1:
    world: 'flatroom'
    x: 45.9
    y: -59.0
    z: -0.7
    yaw: -179.4
    pitch: 0.8






